'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Action_Timer_2.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property AL_Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AL_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property AL_NextTo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AL_NextTo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property AL_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AL_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property AL_Skip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AL_Skip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property AL_Success() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AL_Success", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_md_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_md_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_md_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_md_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_md_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_md_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_md_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_md_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_mm_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_mm_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_mm_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_mm_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_mm_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_mm_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_mm_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_mm_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_n_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_n_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_n_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_n_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_n_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_n_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property audio_n_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_n_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BackGround() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackGround", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_ABOUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_ABOUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_ACTION_LIST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_ACTION_LIST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_CANCEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_CANCEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_EMPTY_RECYCLE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_EMPTY_RECYCLE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_HIBERNATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_HIBERNATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_LOCK_COMPUTER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_LOCK_COMPUTER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_LOGOFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_LOGOFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property md_minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("md_minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_PAUSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_PAUSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_PROCESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_PROCESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_QUICK_ACTION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_QUICK_ACTION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_REMINDER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_REMINDER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_RESTART() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_RESTART", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_SCREEN_SAVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_SCREEN_SAVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_SETTING() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_SETTING", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_SHUT_DOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_SHUT_DOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_SKIP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_SKIP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_STAND_BY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_STAND_BY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_START() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_START", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_STATUS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_STATUS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_STOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_STOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_SYSTEM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_SYSTEM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_TURN_OFF_MONITOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_TURN_OFF_MONITOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_TURN_ON_MONITOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_TURN_ON_MONITOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_UNHIBERNATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_UNHIBERNATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MD_UPDATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MD_UPDATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_CANCEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_CANCEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_Empty_Recycle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_Empty_Recycle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_FUNCTION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_FUNCTION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_hibernate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_hibernate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_lock_COMPUTER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_lock_COMPUTER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_log_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_log_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property mm_minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mm_minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_PAUSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_PAUSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_Screen_Saver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_Screen_Saver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_shut_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_shut_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_SKIP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_SKIP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_stand_by() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_stand_by", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_START() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_START", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_STOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_STOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_TAB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_TAB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_turn_off_monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_turn_off_monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_TURN_ON_MONITOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_TURN_ON_MONITOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_UNHIBERNATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_UNHIBERNATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property MM_UPDATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM_UPDATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_CANCEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_CANCEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_Empty_Recycle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_Empty_Recycle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_hibernate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_hibernate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_lock_COMPUTER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_lock_COMPUTER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_log_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_log_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property n_minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("n_minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_PAUSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_PAUSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_Screen_Saver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_Screen_Saver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_shut_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_shut_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_SKIP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_SKIP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_stand_by() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_stand_by", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_START() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_START", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_STOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_STOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_turn_off_monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_turn_off_monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_TURN_ON_MONITOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_TURN_ON_MONITOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_UNHIBERNATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_UNHIBERNATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property N_UPDATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_UPDATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property status_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("status_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property status_run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("status_run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property status_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("status_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
